name: Test daq-buildtools

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      dbt-branch:
        type: string
        default: 'develop'
        description: "Branch from which to run test_daq-buildtools.sh"

jobs:
  test_daq_buildtools:
    name: Test daq-buildtools
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v5
      with:
        cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'
    - name: Check CVMFS
      run: |
        ls -lrt /cvmfs || exit 1
    - id: checkout_daq_buildtools
      uses: actions/checkout@v6
      with:
        path: daq-buildtools-test
        persist-credentials: false

    - name: Run test_daq-buildtools script
      run: |
        cd daq-buildtools-test
        source env.sh
        cd scripts
        #./test_daq-buildtools.sh --dbt-branch ${{ github.head_ref }}
        docker run --rm \
          --mount type=bind,src=/cvmfs,dst=/cvmfs,bind-propagation=shared \
          --mount type=bind,src="$PWD",dst=/workspace,bind-propagation=shared \
          -w /workspace \
          ghcr.io/dune-daq/nightly-release-alma9:development_v5 \
          ./test_daq-buildtools.sh --dbt-branch ${{ github.head_ref }}

        

