name: Test daq-buildtools

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      dbt-branch:
        type: string
        default: 'develop'
        description: "Branch from which to run test_daq-buildtools.sh"

jobs:
  test_daq_buildtools:
    name: Test daq-buildtools
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v5
      with:
        cvmfs_repositories: 'dunedaq-development.opensciencegrid.org'

    - name: Pull latest nightly build image
      run: docker pull ghcr.io/dune-daq/nightly-release-alma9:development_v5

    - id: checkout_daq_buildtools
      uses: actions/checkout@v6
      with:
        path: daq-buildtools-test
        persist-credentials: false

    - name: Run test_daq-buildtools script
      run: |
        BRANCH="${{ inputs.dbt-branch || github.head_ref || github.ref_name }}"
        cd daq-buildtools-test
        source env.sh
        cd scripts
        docker run --rm \
          -v /cvmfs:/cvmfs:shared \
          -v "$PWD":/workspace \
          -w /workspace \
          ghcr.io/dune-daq/nightly-release-alma9:development_v5 \
          ./test_daq-buildtools.sh --dbt-branch $BRANCH

        

